/* application.fam exporter — the Flipper Application Manifest uFBT reads to
 * build, name and package the .fap. Output is Python-literal `App(...)`.
 *
 * The repo's CI (JS-Apps/scripts/validate.mjs) parses this file with a
 * loose first-match `field="value"` regex and requires:
 *   - appid == folder name (after kebab->snake normalisation)
 *   - entry_point present as a symbol in some .c in the folder
 * So we force appid === namespace === folder(normalised) and emit each
 * field exactly once, double-quoted, with `appid=` / `entry_point=` tokens
 * kept out of any comment.
 */

import { safeNs, pascal } from "./scene.js";

/* Common Flipper app categories (SD-card folder under /ext/apps/). */
export const FAP_CATEGORIES = [
  "Examples", "Tools", "Games", "Media", "NFC", "Sub-GHz",
  "Infrared", "GPIO", "Bluetooth", "USB", "Misc",
];

/* Derive the canonical, build-ready identifiers from app settings. One
 * source of truth so the FAM, the entry .c and the bundle folder agree. */
export function appMeta(state) {
  const a = state.app || {};
  const ns = safeNs(a.namespace || a.name || "app");
  const requires = Array.isArray(a.requires) && a.requires.length
    ? a.requires.filter((r) => /^[a-z0-9_]+$/i.test(r))
    : ["gui"];
  if (!requires.includes("gui")) requires.unshift("gui");
  return {
    ns,
    appid: ns,
    folder: ns.replace(/_/g, "-"),
    entry: `${ns}_app`,
    prefix: pascal(a.name || ns),
    name: (a.name || ns).slice(0, 40),
    category: a.category || "Examples",
    stackSize: Math.max(1, Math.min(8, parseInt(a.stackSize, 10) || 2)),
    requires,
    description: a.description || "Built with Flipper GUI Studio.",
    author: a.author || "Flipper GUI Studio",
    version: a.version || "1.0",
    weburl: a.weburl || "https://tools.ranzlappen.com/flipper-gui/",
    iconMode: a.iconMode === "assets" ? "assets" : "png",
  };
}

function py(s) {
  return '"' + String(s ?? "").replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, " ") + '"';
}

/* True when some icon widget points at an icon — so assets mode knows
 * whether an images/ folder (and fap_icon_assets) will actually exist. */
export function hasReferencedIcons(state) {
  const used = new Set();
  for (const s of state.screens || []) {
    for (const w of s.widgets || []) {
      if (w.type === "icon" && w.iconId) used.add(w.iconId);
    }
  }
  return (state.icons || []).some((i) => used.has(i.id));
}

export function exportFam(state) {
  const m = appMeta(state);
  const requiresList = "[" + m.requires.map((r) => py(r)).join(", ") + "]";
  // fap_icon (launcher) is always present; fap_icon_assets is only added in
  // assets mode when there are icons to compile (an empty images/ fails uFBT).
  const iconLines = [`    fap_icon="icon.png",`];
  if (m.iconMode === "assets" && hasReferencedIcons(state)) {
    iconLines.push(`    fap_icon_assets="images",`);
  }

  const text = `# Flipper Application Manifest — generated by Flipper GUI Studio.
# Keep this file next to ${m.appid}.c and build with: ufbt

App(
    appid=${py(m.appid)},
    name=${py(m.name)},
    apptype=FlipperAppType.EXTERNAL,
    entry_point=${py(m.entry)},
    requires=${requiresList},
    stack_size=${m.stackSize} * 1024,
    fap_category=${py(m.category)},
${iconLines.join("\n")}
    fap_author=${py(m.author)},
    fap_version=${py(m.version)},
    fap_description=${py(m.description)},
    fap_weburl=${py(m.weburl)},
)
`;
  return { filename: "application.fam", text };
}
