#!/usr/bin/env node
/* Add the 8×8 size to the predefined icon library — headless, no browser.
 *
 * The canonical pipeline (generate-icons.mjs) rasterizes the SVG glyphs at
 * each size via Playwright/Chromium. Where no browser is available, this
 * one-shot helper instead derives the 8×8 bitmaps by 2×2 box-downsampling the
 * already-committed, canonical 16×16 bitmaps through the SAME 1-bit pipeline
 * (../lib/xbm.js), then rewrites ../lib/icons/library.js with a "8" entry
 * first in every icon's `sizes` map.
 *
 * Deterministic, dependency-free:
 *   cd tools/flipper-gui && node icongen/downsample-8.mjs
 *
 * Prefer `generate-icons.mjs` (SVG-accurate) when Chromium is installable;
 * both emit the same file shape.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { unpackXbm, packXbm, bytesToB64, b64ToBytes } from "../lib/xbm.js";

const here = dirname(fileURLToPath(import.meta.url));

/* 16×16 → 8×8: each target pixel is on when ≥2 of its 4 source subpixels are. */
function downsample16to8(b64) {
  const src = unpackXbm(b64ToBytes(b64), 16, 16);
  const dst = new Uint8Array(8 * 8);
  for (let y = 0; y < 8; y++) {
    for (let x = 0; x < 8; x++) {
      const sx = x * 2, sy = y * 2;
      const sum =
        src[sy * 16 + sx] + src[sy * 16 + sx + 1] +
        src[(sy + 1) * 16 + sx] + src[(sy + 1) * 16 + sx + 1];
      dst[y * 8 + x] = sum >= 2 ? 1 : 0;
    }
  }
  return bytesToB64(packXbm(dst, 8, 8));
}

/* Mirror generate-icons.mjs's serialize(), with "8" first. */
function serialize(categories) {
  let body = "/* Generated by icongen/generate-icons.mjs — do not edit by hand. */\n";
  body += "export default {\n  categories: [\n";
  for (const cat of categories) {
    body += `    { id: ${JSON.stringify(cat.id)}, label: ${JSON.stringify(cat.label)}, icons: [\n`;
    for (const ic of cat.icons) {
      const s = ic.sizes;
      body += `      { name: ${JSON.stringify(ic.name)}, sizes: { "8": ${JSON.stringify(s["8"])}, "16": ${JSON.stringify(s["16"])}, "32": ${JSON.stringify(s["32"])}, "64": ${JSON.stringify(s["64"])} } },\n`;
    }
    body += "    ] },\n";
  }
  body += "  ],\n};\n";
  return body;
}

async function main() {
  const { default: library } = await import("../lib/icons/library.js");
  let count = 0;
  const categories = library.categories.map((cat) => ({
    id: cat.id,
    label: cat.label,
    icons: cat.icons.map((ic) => {
      const s = ic.sizes;
      count++;
      return { name: ic.name, sizes: { "8": downsample16to8(s["16"]), "16": s["16"], "32": s["32"], "64": s["64"] } };
    }),
  }));

  const out = join(here, "..", "lib", "icons", "library.js");
  writeFileSync(out, serialize(categories));
  console.log(`Added 8×8 to ${count} icons → lib/icons/library.js`);
}

main().catch((err) => { console.error(err); process.exit(1); });
