/* Entry-point exporter — the small <appid>.c that application.fam's
 * entry_point resolves to. It allocates the generated scene, runs the
 * blocking input loop, and frees it. This is also where the host app
 * reacts to custom events: <ns>_on_event() is declared (and given a weak
 * default) in the scene module, and overridden here with a real body the
 * user fills in.
 */

import { appMeta } from "./fam.js";

export function exportEntry(state) {
  const m = appMeta(state);

  const text = `/* ${m.name} — app entry point. Generated by Flipper GUI Studio. */

#include "${m.ns}_scene.h"
#include <furi.h>

/* Called whenever a button's custom event fires. This overrides the weak
 * default in ${m.ns}_scene.c — put your app logic here. */
void ${m.ns}_on_event(int32_t event, ${m.prefix}Model* state) {
    UNUSED(state);
    switch(event) {
        // case 1: /* handle custom event 1 */ break;
        default:
            UNUSED(event);
            break;
    }
}

int32_t ${m.entry}(void* p) {
    UNUSED(p);
    ${m.prefix}Scene* scene = ${m.ns}_scene_alloc();
    ${m.ns}_scene_run(scene);
    ${m.ns}_scene_free(scene);
    return 0;
}
`;
  return { filename: `${m.ns}.c`, text };
}
