/* XBM exporter — emits a header file containing all defined icons,
 * regardless of whether they're referenced by widgets. Useful when
 * you only want the assets, not the scene scaffold. */

import { bytesToCArray, b64ToBytes } from "../lib/xbm.js";
import { safeNs } from "./scene.js";

export function exportXbm(state) {
  const ns = safeNs(state.app.namespace || state.app.name || "app");
  const icons = state.icons || [];
  if (icons.length === 0) {
    return {
      filename: `${ns}_icons.h`,
      text: `#pragma once\n\n/* No icons defined yet. */\n`,
    };
  }
  const decls = icons.map((icon) => {
    const bytes = b64ToBytes(icon.bits || "");
    return `// ${icon.name} ${icon.w}x${icon.h}
static const uint8_t ${icon.name}[] = {
${bytesToCArray(bytes)}
};`;
  }).join("\n\n");

  const text = `#pragma once

/* Generated by Flipper GUI Studio. Use with canvas_draw_xbm():
 *   canvas_draw_xbm(canvas, x, y, W, H, ${icons[0].name});
 */

#include <stdint.h>

${decls}
`;
  return { filename: `${ns}_icons.h`, text };
}
