#!/usr/bin/env node
/* Inject the hand-drawn 8×8 icon art into the committed library — headless.
 *
 * The 8px tier is authored by hand in icons-8px.mjs (the SVG raster is
 * illegible that small). This one-shot helper packs that art and rewrites
 * ../lib/icons/library.js so every icon's `sizes["8"]` is the hand-drawn
 * bitmap, leaving the SVG-rendered 16/32/64 tiers untouched. No browser, no
 * network, deterministic:
 *
 *   cd tools/flipper-gui && node icongen/build-8px.mjs
 *
 * Re-run after editing ART_8. The full generate-icons.mjs (which also uses
 * this art for size 8) is only needed when the 16/32/64 glyphs change.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { ART_8, pack8 } from "./icons-8px.mjs";

const here = dirname(fileURLToPath(import.meta.url));

/* Mirror generate-icons.mjs's serialize(), with "8" first. */
function serialize(categories) {
  let body = "/* Generated by icongen/generate-icons.mjs — do not edit by hand. */\n";
  body += "export default {\n  categories: [\n";
  for (const cat of categories) {
    body += `    { id: ${JSON.stringify(cat.id)}, label: ${JSON.stringify(cat.label)}, icons: [\n`;
    for (const ic of cat.icons) {
      const s = ic.sizes;
      body += `      { name: ${JSON.stringify(ic.name)}, sizes: { "8": ${JSON.stringify(s["8"])}, "16": ${JSON.stringify(s["16"])}, "32": ${JSON.stringify(s["32"])}, "64": ${JSON.stringify(s["64"])} } },\n`;
    }
    body += "    ] },\n";
  }
  body += "  ],\n};\n";
  return body;
}

async function main() {
  const { default: library } = await import("../lib/icons/library.js");

  // Fail loudly if art and library drift apart.
  const libNames = new Set();
  for (const c of library.categories) for (const ic of c.icons) libNames.add(ic.name);
  const missing = [...libNames].filter((n) => !ART_8[n]);
  const extra = Object.keys(ART_8).filter((n) => !libNames.has(n));
  if (missing.length) throw new Error(`No 8×8 art for: ${missing.join(", ")}`);
  if (extra.length) console.warn(`Warning: ART_8 has unused entries: ${extra.join(", ")}`);

  let count = 0;
  const categories = library.categories.map((cat) => ({
    id: cat.id,
    label: cat.label,
    icons: cat.icons.map((ic) => {
      const s = ic.sizes;
      count++;
      return { name: ic.name, sizes: { "8": pack8(ic.name), "16": s["16"], "32": s["32"], "64": s["64"] } };
    }),
  }));

  const out = join(here, "..", "lib", "icons", "library.js");
  writeFileSync(out, serialize(categories));
  console.log(`Wrote hand-drawn 8×8 art for ${count} icons → lib/icons/library.js`);
}

main().catch((err) => { console.error(err); process.exit(1); });
