#!/usr/bin/env node
/* Icon library generator for Flipper GUI Studio.
 *
 * Rasterizes the original SVG glyphs in icons.svg.mjs at 16/32/64 px and
 * packs each through the SAME 1-bit pipeline the tool uses for uploaded
 * images (../lib/xbm.js: imageDataToBits → packXbm → bytesToB64), so
 * library icons are byte-identical to uploads and export with zero
 * special-casing.
 *
 * Output: ../lib/icons/library.js — a committed ES module loaded lazily
 * by the icon picker. NOT part of the site build; rerun only when the
 * glyph set changes:
 *
 *   cd tools/flipper-gui
 *   PLAYWRIGHT_BROWSERS_PATH=/path/to/browsers \
 *   NODE_PATH=/path/to/global/node_modules \
 *   node icongen/generate-icons.mjs
 *
 * Requires Playwright + a Chromium build (used only to rasterize SVG to a
 * canvas — there is no headless SVG rasterizer in plain Node).
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { createRequire } from "node:module";

import { ICONS, CATEGORIES, VIEWBOX } from "./icons.svg.mjs";
import { imageDataToBits, packXbm, bytesToB64 } from "../lib/xbm.js";
import { pack8 } from "./icons-8px.mjs";

const require = createRequire(import.meta.url);
const { chromium } = require("playwright");

const here = dirname(fileURLToPath(import.meta.url));
const SIZES = [8, 16, 32, 64];

async function rasterize(page, inner, size) {
  return page.evaluate(async ({ inner, size, vb }) => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${vb} ${vb}" width="${size}" height="${size}">${inner}</svg>`;
    const url = "data:image/svg+xml;charset=utf-8," + encodeURIComponent(svg);
    const img = new Image();
    await new Promise((res, rej) => { img.onload = res; img.onerror = rej; img.src = url; });
    if (img.decode) { try { await img.decode(); } catch (_) { /* already loaded */ } }
    const c = document.createElement("canvas");
    c.width = size; c.height = size;
    const ctx = c.getContext("2d");
    ctx.imageSmoothingEnabled = true;
    ctx.clearRect(0, 0, size, size);
    ctx.drawImage(img, 0, 0, size, size);
    return Array.from(ctx.getImageData(0, 0, size, size).data);
  }, { inner, size, vb: VIEWBOX });
}

function packForSize(pixels, size, dither) {
  const data = Uint8ClampedArray.from(pixels);
  const bits = imageDataToBits({ data }, size, size, { threshold: 128, dither: !!dither });
  return bytesToB64(packXbm(bits, size, size));
}

function serialize(categories) {
  let body = "/* Generated by icongen/generate-icons.mjs — do not edit by hand. */\n";
  body += "export default {\n  categories: [\n";
  for (const cat of categories) {
    body += `    { id: ${JSON.stringify(cat.id)}, label: ${JSON.stringify(cat.label)}, icons: [\n`;
    for (const ic of cat.icons) {
      const s = ic.sizes;
      body += `      { name: ${JSON.stringify(ic.name)}, sizes: { "8": ${JSON.stringify(s[8])}, "16": ${JSON.stringify(s[16])}, "32": ${JSON.stringify(s[32])}, "64": ${JSON.stringify(s[64])} } },\n`;
    }
    body += "    ] },\n";
  }
  body += "  ],\n};\n";
  return body;
}

async function main() {
  const browser = await chromium.launch();
  const page = await browser.newPage();

  const byCat = new Map(CATEGORIES.map((c) => [c.id, []]));
  for (const icon of ICONS) {
    const sizes = {};
    for (const size of SIZES) {
      // 8px is hand-drawn (icons-8px.mjs) — rasterizing the SVG that small is
      // illegible. Every other tier comes from the SVG raster.
      if (size === 8) { sizes[8] = pack8(icon.name); continue; }
      const pixels = await rasterize(page, icon.inner, size);
      sizes[size] = packForSize(pixels, size, icon.dither);
    }
    byCat.get(icon.category).push({ name: icon.name, sizes });
  }
  await browser.close();

  const categories = CATEGORIES.map((c) => ({ id: c.id, label: c.label, icons: byCat.get(c.id) }));
  const outDir = join(here, "..", "lib", "icons");
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, "library.js"), serialize(categories));

  let total = 0;
  for (const cat of categories) {
    console.log(`  ${cat.id.padEnd(8)} ${cat.icons.length} icons`);
    total += cat.icons.length;
  }
  console.log(`Wrote lib/icons/library.js — ${total} icons × ${SIZES.length} sizes.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
