// Cookies.txt Converter — turn a cookie export (extension JSON or a Cookie:
// header) into a yt-dlp-ready Netscape cookies.txt. Entirely client-side;
// nothing is uploaded.

const $ = (id) => document.getElementById(id);

const els = {
  input: $("ck-input"),
  domain: $("ck-domain"),
  filter: $("ck-filter"),
  output: $("ck-output"),
  status: $("ck-status"),
  copy: $("ck-copy"),
};

const HEADER =
  "# Netscape HTTP Cookie File\n" +
  "# Generated by tools.ranzlappen.com/cookies-txt/ — keep this file private.\n" +
  "# This is a generated file! Do not edit.\n\n";

const LOGIN_COOKIES = ["SID", "HSID", "SSID", "__Secure-1PSID", "__Secure-3PSID", "LOGIN_INFO"];

const SAMPLE = JSON.stringify(
  [
    { domain: ".youtube.com", name: "SID", value: "EXAMPLE-not-a-real-cookie", path: "/", secure: true, httpOnly: false, hostOnly: false, expirationDate: 1893456000 },
    { domain: ".youtube.com", name: "__Secure-3PSID", value: "EXAMPLE-value", path: "/", secure: true, httpOnly: true, hostOnly: false, expirationDate: 1893456000 },
    { domain: ".youtube.com", name: "PREF", value: "tz=UTC", path: "/", secure: true, httpOnly: false, hostOnly: false, expirationDate: 1893456000 },
  ],
  null,
  2
);

function normalizeDomain(c) {
  let dom = String(c.domain || "").trim();
  let includeSub;
  if (c.hostOnly === true) {
    includeSub = false;
    if (dom.startsWith(".")) dom = dom.slice(1);
  } else if (c.hostOnly === false) {
    includeSub = true;
    if (dom && !dom.startsWith(".")) dom = "." + dom;
  } else {
    includeSub = dom.startsWith(".");
  }
  return { dom, includeSub };
}

function expiryOf(c) {
  let e = c.expirationDate ?? c.expires ?? c.expiry;
  if (e == null) return 0; // session cookie
  if (typeof e === "string") {
    const ms = Date.parse(e);
    if (!Number.isNaN(ms)) return Math.floor(ms / 1000);
    const f = parseFloat(e);
    return Number.isNaN(f) ? 0 : Math.floor(f);
  }
  return Math.floor(e);
}

function parseInput(text, headerDomain) {
  text = text.trim();
  if (!text) return { kind: "empty", cookies: [] };

  if (text[0] === "[" || text[0] === "{") {
    let data;
    try {
      data = JSON.parse(text);
    } catch (e) {
      return { error: "Invalid JSON — " + e.message };
    }
    let arr = Array.isArray(data) ? data : Array.isArray(data.cookies) ? data.cookies : [data];
    const cookies = arr
      .filter((o) => o && typeof o === "object" && o.name != null)
      .map((o) => ({
        domain: o.domain || o.host || headerDomain,
        name: String(o.name),
        value: o.value == null ? "" : String(o.value),
        path: o.path || "/",
        secure: !!o.secure,
        httpOnly: !!(o.httpOnly || o.httponly),
        hostOnly: o.hostOnly,
        expirationDate: o.expirationDate ?? o.expires ?? o.expiry,
      }));
    return { kind: "json", cookies };
  }

  // Cookie: header form — name=value; name2=value2
  const cookies = [];
  text
    .replace(/^cookie:\s*/i, "")
    .split(/;\s*/)
    .forEach((pair) => {
      const i = pair.indexOf("=");
      if (i <= 0) return;
      const name = pair.slice(0, i).trim();
      const value = pair.slice(i + 1).trim();
      if (!name) return;
      cookies.push({ domain: headerDomain, name, value, path: "/", secure: true, httpOnly: false, hostOnly: false });
    });
  return { kind: "header", cookies };
}

function toNetscape(cookies, filter) {
  const now = Date.now() / 1000;
  const lines = [];
  let expired = 0;
  for (const c of cookies) {
    if (!c.name) continue;
    const { dom, includeSub } = normalizeDomain(c);
    if (!dom) continue;
    if (filter && !dom.replace(/^\./, "").toLowerCase().includes(filter)) continue;
    const exp = expiryOf(c);
    if (exp && exp < now) expired++;
    const domField = (c.httpOnly ? "#HttpOnly_" : "") + dom;
    lines.push(
      [domField, includeSub ? "TRUE" : "FALSE", c.path || "/", c.secure ? "TRUE" : "FALSE", String(exp), c.name, c.value].join("\t")
    );
  }
  return { lines, kept: lines.length, expired };
}

function setStatus(type, msg) {
  els.status.className = "banner banner--" + type;
  els.status.textContent = msg;
}
function hideStatus() {
  els.status.className = "banner is-hidden";
  els.status.textContent = "";
}

function render() {
  const headerDomain = els.domain.value.trim() || ".youtube.com";
  const filter = els.filter.value.trim().toLowerCase();
  const res = parseInput(els.input.value, headerDomain);

  if (res.error) {
    setStatus("error", res.error);
    els.output.textContent = "";
    els.output.dataset.text = "";
    return;
  }
  if (res.kind === "empty") {
    hideStatus();
    els.output.textContent = "";
    els.output.dataset.text = "";
    return;
  }

  const { lines, kept, expired } = toNetscape(res.cookies, filter);
  const text = lines.length ? HEADER + lines.join("\n") + "\n" : "";
  els.output.textContent = text;
  els.output.dataset.text = text;

  if (!kept) {
    setStatus(
      "warn",
      "No cookies found. Paste a JSON array from a cookie-export extension, or a “name=value; …” Cookie header."
    );
    return;
  }

  const names = new Set(res.cookies.map((c) => c.name));
  const signedIn = LOGIN_COOKIES.some((n) => names.has(n));
  let cls = "info";
  let msg = `${kept} cookie${kept === 1 ? "" : "s"} converted` +
    (res.kind === "header" ? ` for ${headerDomain}` : "") +
    (filter ? ` (filtered to “${filter}”)` : "") + ".";
  if (expired) {
    cls = "warn";
    msg += ` ${expired} appear expired.`;
  }
  if (!signedIn) {
    msg += " No Google login cookies (SID / __Secure-3PSID) detected — you may not be signed in.";
    if (cls === "info") cls = "warn";
  }
  setStatus(cls, msg);
}

function downloadTxt() {
  const text = els.output.dataset.text || "";
  if (!text) return;
  const blob = new Blob([text], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "cookies.txt";
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

// ---- events ----

["input", "domain", "filter"].forEach((k) => {
  els[k].addEventListener("input", render);
});

document.addEventListener("click", async (ev) => {
  const action = ev.target.closest("[data-action]")?.dataset.action;
  if (!action) return;
  if (action === "sample") {
    els.input.value = SAMPLE;
    render();
  } else if (action === "clear") {
    els.input.value = "";
    els.input.focus();
    render();
  } else if (action === "download") {
    downloadTxt();
  } else if (action === "copy") {
    const text = els.output.dataset.text || "";
    if (!text) return;
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      const r = document.createRange();
      r.selectNodeContents(els.output);
      const sel = getSelection();
      sel.removeAllRanges();
      sel.addRange(r);
    }
    const original = els.copy.lastChild.textContent;
    els.copy.lastChild.textContent = " Copied";
    setTimeout(() => { els.copy.lastChild.textContent = original; }, 1200);
  }
});

render();
