/* Curated Google Fonts (open-license) with verified jsDelivr `gh/google/fonts`
   TTF paths. `slug`/`dir`/`file` resolve to a real .ttf so it embeds straight
   into the theme. Arbitrary families are resolved at runtime in fonts.js via
   each family's METADATA.pb, so this list is just the featured quick-picks. */

export const CURATED_FONTS = [
  { family: "Roboto", slug: "roboto", dir: "ofl", file: "Roboto[wdth,wght].ttf" },
  { family: "Open Sans", slug: "opensans", dir: "ofl", file: "OpenSans[wdth,wght].ttf" },
  { family: "Lato", slug: "lato", dir: "ofl", file: "Lato-Regular.ttf" },
  { family: "Montserrat", slug: "montserrat", dir: "ofl", file: "Montserrat[wght].ttf" },
  { family: "Oswald", slug: "oswald", dir: "ofl", file: "Oswald[wght].ttf" },
  { family: "Raleway", slug: "raleway", dir: "ofl", file: "Raleway[wght].ttf" },
  { family: "Poppins", slug: "poppins", dir: "ofl", file: "Poppins-Regular.ttf" },
  { family: "Noto Sans", slug: "notosans", dir: "ofl", file: "NotoSans[wdth,wght].ttf" },
  { family: "Roboto Condensed", slug: "robotocondensed", dir: "ofl", file: "RobotoCondensed[wght].ttf" },
  { family: "Roboto Mono", slug: "robotomono", dir: "ofl", file: "RobotoMono[wght].ttf" },
  { family: "Inter", slug: "inter", dir: "ofl", file: "Inter[opsz,wght].ttf" },
  { family: "Ubuntu", slug: "ubuntu", dir: "ufl", file: "Ubuntu-Regular.ttf" },
  { family: "Merriweather", slug: "merriweather", dir: "ofl", file: "Merriweather[opsz,wdth,wght].ttf" },
  { family: "Playfair Display", slug: "playfairdisplay", dir: "ofl", file: "PlayfairDisplay[wght].ttf" },
  { family: "Nunito", slug: "nunito", dir: "ofl", file: "Nunito[wght].ttf" },
  { family: "Rubik", slug: "rubik", dir: "ofl", file: "Rubik[wght].ttf" },
  { family: "Work Sans", slug: "worksans", dir: "ofl", file: "WorkSans[wght].ttf" },
  { family: "Fira Sans", slug: "firasans", dir: "ofl", file: "FiraSans-Regular.ttf" },
  { family: "PT Sans", slug: "ptsans", dir: "ofl", file: "PT_Sans-Web-Regular.ttf" },
  { family: "Roboto Slab", slug: "robotoslab", dir: "apache", file: "RobotoSlab[wght].ttf" },
  { family: "DM Sans", slug: "dmsans", dir: "ofl", file: "DMSans[opsz,wght].ttf" },
  { family: "Space Grotesk", slug: "spacegrotesk", dir: "ofl", file: "SpaceGrotesk[wght].ttf" },
  { family: "JetBrains Mono", slug: "jetbrainsmono", dir: "ofl", file: "JetBrainsMono[wght].ttf" },
  { family: "Source Code Pro", slug: "sourcecodepro", dir: "ofl", file: "SourceCodePro[wght].ttf" },
  { family: "Bebas Neue", slug: "bebasneue", dir: "ofl", file: "BebasNeue-Regular.ttf" },
  { family: "Quicksand", slug: "quicksand", dir: "ofl", file: "Quicksand[wght].ttf" },
  { family: "Mulish", slug: "mulish", dir: "ofl", file: "Mulish[wght].ttf" },
  { family: "Manrope", slug: "manrope", dir: "ofl", file: "Manrope[wght].ttf" },
  { family: "Karla", slug: "karla", dir: "ofl", file: "Karla[wght].ttf" },
  { family: "Josefin Sans", slug: "josefinsans", dir: "ofl", file: "JosefinSans[wght].ttf" },
  { family: "Dancing Script", slug: "dancingscript", dir: "ofl", file: "DancingScript[wght].ttf" },
  { family: "Pacifico", slug: "pacifico", dir: "ofl", file: "Pacifico-Regular.ttf" },
  { family: "Lobster", slug: "lobster", dir: "ofl", file: "Lobster-Regular.ttf" },
  { family: "Comfortaa", slug: "comfortaa", dir: "ofl", file: "Comfortaa[wght].ttf" },
  { family: "Caveat", slug: "caveat", dir: "ofl", file: "Caveat[wght].ttf" },
  { family: "Libre Baskerville", slug: "librebaskerville", dir: "ofl", file: "LibreBaskerville[wght].ttf" },
  { family: "Archivo", slug: "archivo", dir: "ofl", file: "Archivo[wdth,wght].ttf" },
  { family: "Barlow", slug: "barlow", dir: "ofl", file: "Barlow-Regular.ttf" },
  { family: "Titillium Web", slug: "titilliumweb", dir: "ofl", file: "TitilliumWeb-Regular.ttf" },
  { family: "Cabin", slug: "cabin", dir: "ofl", file: "Cabin[wdth,wght].ttf" },
  { family: "Kanit", slug: "kanit", dir: "ofl", file: "Kanit-Regular.ttf" },
  { family: "Heebo", slug: "heebo", dir: "ofl", file: "Heebo[wght].ttf" },
  { family: "Assistant", slug: "assistant", dir: "ofl", file: "Assistant[wght].ttf" },
  { family: "Figtree", slug: "figtree", dir: "ofl", file: "Figtree[wght].ttf" },
  { family: "Source Sans 3", slug: "sourcesans3", dir: "ofl", file: "SourceSans3[wght].ttf" },
  { family: "Source Serif 4", slug: "sourceserif4", dir: "ofl", file: "SourceSerif4[opsz,wght].ttf" },
  { family: "IBM Plex Sans", slug: "ibmplexsans", dir: "ofl", file: "IBMPlexSans[wdth,wght].ttf" },
];
